### ISSUE TITLE
Номер счета типа int

### ISSUE THREAD

**Issue by Muxa89** [Alexander512023/bank#10]
https://github.com/Alexander512023/bank/blob/c2a30b365e761d3ccfdf8a5d0f769089ae464236/Bank/src/main/java/com/goryaninaa/web/Bank/service/account/AccountService.java#L31

Я бы не закладывался на то что номер счета будет int. Проблемы с ним начнутся сразу как только выйдешь за границы int. Обычно такие айдишники задаются через строку.

**Comment by Alexander512023** [comment]
Тут речь ведется именно о последних 4-7 символах, которые снимаются с номерной емкости. Мне кажется здесь int уместен. Он потом уже может объединяться с балансовым счетом, валютой, отделением и это уже хранить в String.

**Comment by Muxa89** [comment]
Если речь о сложносочиненном номере счета - тогда я вообще бы вынес это все в отдельную сущность. Там сразу речь тогда идет что есть какой-то выделенный генератор этих счетов, он будет работать по каким-то своим правилам, которые прямого отошения к счету не имеют, которые имеет смысл вынести в отдельный пласт логики приложения.

**Comment by Alexander512023** [comment]
Будет прорабатываться в рамках https://github.com/Alexander512023/bank/issues/7
