### ISSUE TITLE
AccountService слишком нагружен логикой

### ISSUE THREAD

**Issue by Muxa89** [Alexander512023/bank#11]
https://github.com/Alexander512023/bank/blob/c2a30b365e761d3ccfdf8a5d0f769089ae464236/Bank/src/main/java/com/goryaninaa/web/Bank/service/account/AccountService.java#L32

Надо подумать как можно отрефакторить AccountService. 
Есть ощущение что в нем смешалась бизнес-логика (управление entity) и служебная логика (обогащение и создание транзакций).

Ну и транзакции напрашиваются на выделение в какую-то структуру классов.

**Comment by Alexander512023** [comment]
Тоже пока писал на самом деле достаточно много тут думал, как это все разнести. Но как-то показалось, что квант действий, включаемых в методы типа deposit и withdraw минимален. Мотивация - нам надо баланс зафиксировать до проведения операции и после проведения операции, чтобы это у нас рассинхрона не появилось. Я там эти действия даже в synchronized блок добавил. Правда он пока некорректно/не до конца реализован, но это верно именно с логической точки зрения на мой взгляд.

Если подвести мини-итог, получается, что проведение операции и генерация соответствующей транзакции это единый кусок логики и должно быть внутри одного метода..

Возможно там надо стратегию применить, чтобы сам класс не перегружать. Думаю тут надо также к сессии очного обсуждения вопрос подтянуть.

**Comment by Muxa89** [comment]
Ну да, надо обсудить. У тебя в сервисе перемешалась служебная логика и бизнес-логика. И бизнес-логику имеет смысл вытащить в отдельные "юзкейсы".

**Comment by Alexander512023** [comment]
Переписал публичные методы в сервисе. Как на твой взгляд, достаточно таких правок?

	public void open(AccountOpenRequisites requisites) throws AccountOpenException {
		Account account = openAccount(requisites);
		Transaction openAccountTransaction = createOpenAccountTransaction(requisites, account);
		accountRepository.save(account);
		transactionRepository.save(openAccountTransaction);
	}
	
	public void deposit(TransactionRequisites requisites) throws AccountFindException, AccountDepositException {
		Account account = findByNumber(requisites.getAccountRecepient().getNumber());
		account.deposit(requisites.getAmount());
		Transaction deposit = generateDepositTransaction(requisites, account);
		accountRepository.update(account);
		transactionRepository.save(deposit);
	}
	
	public void withdraw(TransactionRequisites requisites) throws AccountFindException, AccountWithdrawException {
		Account account = findByNumber(requisites.getAccountFrom().getNumber());
		account.withdraw(requisites.getAmount());
		Transaction withdraw = generateWithdrawTransaction(requisites, account);
		accountRepository.update(account);
		transactionRepository.save(withdraw);
	}

	public void transfer(TransactionRequisites requisites)
			throws AccountFindException, AccountDepositException, AccountWithdrawException  {
		deposit(requisites);
		withdraw(requisites);
	}
	
	public Account findByNumber(int number) throws AccountFindException {
		Account account = findAccount(number);
		return account;
	}

**Comment by Alexander512023** [comment]
Логика из AccountService частично перенесена в новые сущности: OperationService, RequisiteService.
https://github.com/Alexander512023/bank/commit/8838965b15c2dcb5cf204be4cbae6a17b816420e
