### ISSUE TITLE
4 проекта

### ISSUE THREAD

**Issue by Muxa89** [Alexander512023/bank#12]
4 разные репы с частями одного большого проекта выглядят непонятно. Я бы предложил им всем добавить префикс - например BankingApp, чтобы было понятно что это все составляющие одного проекта. Ну и надо задуматься, действительно ли правильно все прям так разделять на отдельные проекты. 
Отделение части кода в отдельный проект подразумевает некоторую самостоятельность проекта. А насколько самостоятелен логгер или кэш?

**Comment by Alexander512023** [comment]
В целом это куски кода, которые на банковскую часть никак не завязаны и могут быть использованы отдельно. Но с разделениями тоже для меня не все прозрачно, думаю стоит проговорить.

**Comment by Alexander512023** [comment]
Всю служебную логику, которая сейчас разделена на 3 разных проекта, слить в мини библиотеку/фреймворк.
