### ISSUE TITLE
Нейминг переменных не соответствует содержимому

### ISSUE THREAD

**Issue by Muxa89** [Alexander512023/bank#13]
В main тяжело разбираться когда нейминг переменных так скачет.

https://github.com/Alexander512023/bank/blob/d9544ebab80d998baf468ade9a3c1deb8c45360a/Bank/src/main/java/com/goryaninaa/web/Bank/App.java#L65

`AccountService accountService = new AccountService(accountRepository, transactionRepository, numberCapacityRepository, clientRepository);`

https://github.com/Alexander512023/bank/blob/d9544ebab80d998baf468ade9a3c1deb8c45360a/Bank/src/main/java/com/goryaninaa/web/Bank/App.java#L67

`Controller accountController = new AccountController(balanceService);`

**Comment by Alexander512023** [comment]
Следствия рефактора нейминга. Может идея тут конечно умеет названия переменных подбирать, эклипса - к сожалению нет.
