### ISSUE TITLE
Конкретика по транзакции внутри Account

### ISSUE THREAD

**Issue by Muxa89** [Alexander512023/Bank#14]
https://github.com/Alexander512023/bank/blob/d9544ebab80d998baf468ade9a3c1deb8c45360a/Bank/src/main/java/com/goryaninaa/web/Bank/model/account/Account.java#L16

Не уверен что хранить номер последней транзакции по аккаунту хорошая идея по следующим причинам:
1. Номер последней транзакции - расчетное значение. Ты можешь его высчитывать каждый раз. И если скорость этой операции тебя не устраивает - добавить промежуточный кеш.
2. Транзакции должны знать об аккаунте к которому они относятся, а аккаунт не должен знать об этом ничего.

**Comment by Alexander512023** [comment]
Здесь скорее идея о каком-то агрегате. Сейчас достаточно модная тема - иметь возможность проведения операций без обращения к истории.

**Comment by Muxa89** [comment]
Ну агрегатом в таком случае должен выступать объект "ИсторияТранзакций".

**Comment by Alexander512023** [comment]
Поле LastOperationNumber удалено из сущности Account
4cc282c
