### ISSUE TITLE
Настройки окружения в коде

### ISSUE THREAD

**Issue by Muxa89** [Alexander512023/bank#2]
Мне кажется что лучше будет:
1. Не прописывать полный путь до требуемого файла (использовать относительный)
2. Если требуется хранить подобные настройки - использовать отдельные файлы с конфигами (yaml или env).

https://github.com/Alexander512023/bank/blob/9dd65c04580aa04c10342aae067c5c94efef999f/Bank/src/main/java/com/goryaninaa/web/Bank/App.java#L64

**Comment by Alexander512023** [comment]
Спасибо, интересный вопрос.
Покопался в документации Java. Обнаружил, что Java имеет собственный класс Properties и набрел на StackOverflaw  на интересную рекомендацию - файл для создания объекта класса Properties прямо в рантайме считывать из Classpath через рефлексию. По неймингу, согласно документации Java, предпочтительно использовать *.properties.
Внесены соответствующие изменения в сервер и банк.

**Comment by Alexander512023** [comment]
Настройки лежат по пути /src/main/resources/
