### ISSUE TITLE
Сильная связность двух проектов

### ISSUE THREAD

**Issue by Muxa89** [Alexander512023/bank#3]
https://github.com/Alexander512023/bank/blob/9dd65c04580aa04c10342aae067c5c94efef999f/Bank/src/main/java/com/goryaninaa/web/Bank/App.java#L67

Судя по тому что ты разделил проекты, ты не хотел создавать сильную связность. 
Но, судя по прямым импортам в App.java и AccountController.java, сильная связь все-таки образовалась. 

Если ты ставил перед собой задачу разделения, то я бы предложил в проекте bank что-то из следующего:
- использовать универсальные интерфейсы, которые поставляет Java (если такие есть), и сделать в HttpServer поддержку этих интерфейсов
- создать свой набор интерфейсов, к которым можно будет через адаптер подключить либо твой HttpServer, либо какую-то библиотеку

**Comment by Alexander512023** [comment]
Тут логика была следующая. Как я понял из своих изысканий по архитектуре, зависимости идут на уровне слоев. Соответственно у меня существует выделенный слой под контроллеры, который может работать только с моим сервером, но все низлежащие слои никак не зависят от сервера. На уровне репозитория идет другая зависимость - на кэш. При этом основная задача - исключить из слоя domain logic все возможные зависимости. Это как раз сделано - все интерфейсы развернуты так, чтобы domain logic был максимально независим.
Типа если мы меняем какие-то связки и слои - основная логика работы приложения остается не затронута (что конечно весьма условно, учитывая сколько всего интересного накручено на уровне сервисов).
В общем тут предлагаю обсудить очно..

**Comment by Muxa89** [comment]
Ну да, обсудим. Может быть я неправильно понял твою задумку. Просто мне показалось что было бы круто если бы твой самописный сервер можно было бы с минимальными приседаниями на какую-нибудь либу со стандартным интерфейсом.

**Comment by Alexander512023** [comment]
> Тут логика была следующая. Как я понял из своих изысканий по архитектуре, зависимости идут на уровне слоев. Соответственно у меня существует выделенный слой под контроллеры, который может работать только с моим сервером, но все низлежащие слои никак не зависят от сервера. На уровне репозитория идет другая зависимость - на кэш. При этом основная задача - исключить из слоя domain logic все возможные зависимости. Это как раз сделано - все интерфейсы развернуты так, чтобы domain logic был максимально независим.
> Типа если мы меняем какие-то связки и слои - основная логика работы приложения остается не затронута (что конечно весьма условно, учитывая сколько всего интересного накручено на уровне сервисов).
> В общем тут предлагаю обсудить очно..

Что-то я заотдыхался на НГ - сервисы естественно относятся к domain logic слою, поэтому все ок..

**Comment by Alexander512023** [comment]
Проговорили, что требуется все не связанное с бизнес приложением вынести в отдельный проект типа "фреймворк", чтобы не плодить зависимости.

**Comment by Alexander512023** [comment]
Будет прорабатываться в рамках https://github.com/Alexander512023/bank/issues/12
