### ISSUE TITLE
ServiceInitiator

### ISSUE THREAD

**Issue by Muxa89** [Alexander512023/bank#4]
https://github.com/Alexander512023/bank/blob/9dd65c04580aa04c10342aae067c5c94efef999f/Bank/src/main/java/com/goryaninaa/web/Bank/DTO/AccountRequisitesDTO.java#L52

Вопрос: что это и зачем нужно?

**Comment by Muxa89** [comment]
Код ServiceInitiator я нашел) 
Переформулирую вопрос: 
1. Что такое "сервис-инициатор"?
2. Где это поле применяется? Нигде по коду обращений к этому полю не нашел.

**Comment by Alexander512023** [comment]
Прикладываю пример выходного JSON, который формируется при запросе вклада, на мой взгляд уместно смотрится - понятно по какому каналу мы получили ту или иную транзакцию.

{
    "lastTransactionNumber": 2,
    "balance": 5100000,
    "number": 1001,
    "state": "OPENED",
    "openedAt": "2023-01-12T22:22:40.906984",
    "closedAt": null,
    "owner": {
        "passport": "36 10 000001",
        "firstName": "Alex",
        "secondName": "Goryanin",
        "dateOfBirth": "30.10.1989",
        "products": null
    },
    "historyDTO": [
        {
            "amount": 100000,
            "balanceBefore": 5000000,
            "balanceAfter": 5100000,
            "performedAt": "2023-01-12T22:22:50.787342",
            "accountFromNumber": null,
            "accountRecepientNumber": "1001",
            "clientDTO": {
                "passport": "36 10 000001",
                "firstName": "Alex",
                "secondName": "Goryanin",
                "dateOfBirth": "30.10.1989",
                "products": null
            },
            "service": "POSTMAN",
            "transactionType": "DEPOSIT",
            "historyNumber": 2
        },
        {
            "amount": 5000000,
            "balanceBefore": 0,
            "balanceAfter": 5000000,
            "performedAt": "2023-01-12T22:22:40.905224",
            "accountFromNumber": null,
            "accountRecepientNumber": "1001",
            "clientDTO": {
                "passport": "36 10 000001",
                "firstName": "Alex",
                "secondName": "Goryanin",
                "dateOfBirth": "30.10.1989",
                "products": null
            },
            "service": "POSTMAN",
            "transactionType": "DEPOSIT",
            "historyNumber": 1
        }
    ],
    "type": "VKLAD100",
    "term": 6,
    "prolongationDate": "2023-07-12"
}

**Comment by Muxa89** [comment]
Очень сомневаюсь что если я захочу запросить список счетов мне будет интересно через какой сервис он был открыт. Но даже если это и требуется - то все равно сервис через который был открыт счет имеет большее отношение к транзакции открытия чем к счету непосредственно, как мне кажется.

**Comment by Alexander512023** [comment]
Ну так это в транзакции же и лежит - она как раз в массиве отдается вместе со счетом.

**Comment by Alexander512023** [comment]
> Очень сомневаюсь что если я захочу запросить список счетов мне будет интересно через какой сервис он был открыт. Но даже если это и требуется - то все равно сервис через который был открыт счет имеет большее отношение к транзакции открытия чем к счету непосредственно, как мне кажется.

Тут конечно вопрос - что отдавать? Просто из того что я про REST вычитывал на Habr мы максимально должны клиенту отдать информацию, возможно избыточно. Он сам дальше решает, что с ней делать.

Думаю также стоит обсудить здесь.

**Comment by Muxa89** [comment]
> Ну так это в транзакции же и лежит - она как раз в массиве отдается вместе со счетом.

А, понял. Это получается дтоха которая приходит только на открытие счета.
Тогда я бы нейминг поменял на OpenAccountRequisites или NewAccountRequisites.

**Comment by Alexander512023** [comment]
> > Ну так это в транзакции же и лежит - она как раз в массиве отдается вместе со счетом.
> 
> А, понял. Это получается дтоха которая приходит только на открытие счета. Тогда я бы нейминг поменял на OpenAccountRequisites или NewAccountRequisites.

Не совсем так) Это приходит вообще, когда счет на просмотр запрашивается
Вот так
http://localhost:8080/balance/view?number=1001

**Comment by Muxa89** [comment]
> > Очень сомневаюсь что если я захочу запросить список счетов мне будет интересно через какой сервис он был открыт. Но даже если это и требуется - то все равно сервис через который был открыт счет имеет большее отношение к транзакции открытия чем к счету непосредственно, как мне кажется.
> 
> Тут конечно вопрос - что отдавать? Просто из того что я про REST вычитывал на Habr мы максимально должны клиенту отдать информацию, возможно избыточно. Он сам дальше решает, что с ней делать.
> 
> Думаю также стоит обсудить здесь.

Думаю для учебного приложения это не принципиальный вопрос. Если хочешь все отдавать - отдавай все. В проме это все будет упираться в производительность БД и потребности бизнеса. Для проекта в портфолио вообще не принципиально.

**Comment by Muxa89** [comment]
> > > Ну так это в транзакции же и лежит - она как раз в массиве отдается вместе со счетом.
> > 
> > 
> > А, понял. Это получается дтоха которая приходит только на открытие счета. Тогда я бы нейминг поменял на OpenAccountRequisites или NewAccountRequisites.
> 
> Не совсем так) Это приходит вообще, когда счет на просмотр запрашивается Вот так http://localhost:8080/balance/view?number=1001

Так на "deposit" вообще другая дтоха:
<img width="713" alt="Снимок экрана 2023-01-13 в 10 31 45" src="https://user-images.githubusercontent.com/1621669/212252978-6f11a455-9b20-41ec-98c7-efa565b7d9e5.png">

**Comment by Alexander512023** [comment]
Депозит в переводе со вражеского это взнос

> > > > Ну так это в транзакции же и лежит - она как раз в массиве отдается вместе со счетом.
> > > 
> > > 
> > > А, понял. Это получается дтоха которая приходит только на открытие счета. Тогда я бы нейминг поменял на OpenAccountRequisites или NewAccountRequisites.
> > 
> > 
> > Не совсем так) Это приходит вообще, когда счет на просмотр запрашивается Вот так http://localhost:8080/balance/view?number=1001
> 
> Так на "deposit" вообще другая дтоха: <img alt="Снимок экрана 2023-01-13 в 10 31 45" width="713" src="https://user-images.githubusercontent.com/1621669/212252978-6f11a455-9b20-41ec-98c7-efa565b7d9e5.png">

Депозит в переводе со вражеского это взнос.

**Comment by Muxa89** [comment]
> > > > > Ну так это в транзакции же и лежит - она как раз в массиве отдается вместе со счетом.
> > > > 
> > > > 
> > > > А, понял. Это получается дтоха которая приходит только на открытие счета. Тогда я бы нейминг поменял на OpenAccountRequisites или NewAccountRequisites.
> > > 
> > > 
> > > Не совсем так) Это приходит вообще, когда счет на просмотр запрашивается Вот так http://localhost:8080/balance/view?number=1001
> > 
> > 
> > Так на "deposit" вообще другая дтоха: <img alt="Снимок экрана 2023-01-13 в 10 31 45" width="713" src="https://user-images.githubusercontent.com/1621669/212252978-6f11a455-9b20-41ec-98c7-efa565b7d9e5.png">
> 
> Депозит в переводе со вражеского это взнос)

А, блин) Не туда посмотрел) Ну во view тоже нет AccountRequisitesDTO:
<img width="840" alt="Снимок экрана 2023-01-13 в 10 37 03" src="https://user-images.githubusercontent.com/1621669/212253826-3d46d9e8-e68b-40d5-9053-2303564d6eef.png">

**Comment by Alexander512023** [comment]
> > > > > > Ну так это в транзакции же и лежит - она как раз в массиве отдается вместе со счетом.
> > > > > 
> > > > > 
> > > > > А, понял. Это получается дтоха которая приходит только на открытие счета. Тогда я бы нейминг поменял на OpenAccountRequisites или NewAccountRequisites.
> > > > 
> > > > 
> > > > Не совсем так) Это приходит вообще, когда счет на просмотр запрашивается Вот так http://localhost:8080/balance/view?number=1001
> > > 
> > > 
> > > Так на "deposit" вообще другая дтоха: <img alt="Снимок экрана 2023-01-13 в 10 31 45" width="713" src="https://user-images.githubusercontent.com/1621669/212252978-6f11a455-9b20-41ec-98c7-efa565b7d9e5.png">
> > 
> > 
> > Депозит в переводе со вражеского это взнос)
> 
> А, блин) Не туда посмотрел) Ну во view тоже нет AccountRequisitesDTO: <img alt="Снимок экрана 2023-01-13 в 10 37 03" width="840" src="https://user-images.githubusercontent.com/1621669/212253826-3d46d9e8-e68b-40d5-9053-2303564d6eef.png">

Не в полной мере понял вопрос - сейчас на аккаунте у нас связь один ко многим с транзакциями, соответственно когда мы его вытягиваем, по связи тоже все достается

**Comment by Muxa89** [comment]
Вопрос у меня уже только к названию AccountRequisitesDTO)
Эта ДТО используется только в контроллере open, а выглядит как нечто более абстрактное. Поэтому предлагаю переназвать ее в OpenAccountRequisitesDTO или NewAccountRequisitesDTO и закрыть вопрос)

**Comment by Alexander512023** [comment]
Исправлены наименования на AccountOpenRequisitesDTO, AccountOpenRequisites
