### ISSUE TITLE
Необработанное исключение в enrichAccountRequisites

### ISSUE THREAD

**Issue by Muxa89** [Alexander512023/bank#5]
https://github.com/Alexander512023/bank/blob/9dd65c04580aa04c10342aae067c5c94efef999f/Bank/src/main/java/com/goryaninaa/web/Bank/service/account/AccountService.java#L29

Внутри enrichAccountRequisites если клиент не найден ты кидаешь исключение, которое никак не обрабатывается в контроллере. Контроллер должен возвращать ошибку статусом или определенным форматом сообщения.

**Comment by Alexander512023** [comment]
Добавил в сервис исключения для каждой операции. На контроллере включена обработка всех исключений с отправкой информативного сообщения в JSON на клиента.

AccountOpenException
AccountDepositException
AccountWithdrawException
AccountTransferException
AccountFindException

**Comment by Alexander512023** [comment]
Слегка скорректированы в текущей версии.
Обработка исключений вынесена в контроллер.
Добавлен объект ErrorDTO, который отправляется в случае если при обработке запроса клиента возникла исключительная ситуация.
