### ISSUE TITLE
Модификация аргумента в enrichAccountRequisites

### ISSUE THREAD

**Issue by Muxa89** [Alexander512023/bank#6]
https://github.com/Alexander512023/bank/blob/9dd65c04580aa04c10342aae067c5c94efef999f/Bank/src/main/java/com/goryaninaa/web/Bank/service/account/AccountService.java#L99

Я не уверен, насколько это правильно для Java, но мне кажется, что модификация объекта аргумента это не очень хорошо. Если функция занимается обогащением - я бы явно возвращал новый экземпляр объекта, обогащенный. 

Т.е. сигнатура метода будет выглядеть как-то так:
```
private AccountRequisites enrichAccountRequisites(AccountRequisites requisites) {
```

**Comment by Alexander512023** [comment]
Здесь согласен, меня кое-какой видос смутил где было так сделано. Пофиксил
