### ISSUE TITLE
Генерация номеров счетов

### ISSUE THREAD

**Issue by Muxa89** [Alexander512023/Bank#7]
https://github.com/Alexander512023/bank/blob/9dd65c04580aa04c10342aae067c5c94efef999f/Bank/src/main/java/com/goryaninaa/web/Bank/App.java#L42

Насколько я понял, эта штука нужна чтобы генерить новые номера счетов. Но она получается оторванной от фактического состояния хранилища данных. 
Сейчас ты хранишь данные в кеше, и это норм. Но в будущем нужно будет добавить персистентность. Соответственно генератор номеров счетов должен опираться на состояние хранилища.

**Comment by Muxa89** [comment]
Ну и если я правильно разобрался в назначении - я бы нейминг поменял. Например AccountNumberGenerator.

**Comment by Alexander512023** [comment]
Логика была, что это репозиторий, олицетворяющий связь с некой сторонней системой, которая хранит номерную емкость с простой логикой - при запросе отдает новый номер счета и инкрементирует счетчик. Сейчас приложение с точки зрения БД работает на заглушках, поэтому историчность не поддерживается. Не совсем понятно пересечение с кэшем - обращение к номерной емкости происходит только в момент открытия счета. В кэш это может попасть только на последующих этапах.

**Comment by Muxa89** [comment]
А, то есть кэш это не имитация персистентности?
А зачем он тогда нужен? Кэш обычно добавляется сверху существующего приложения, если есть проблемы по производительности. Ну или если разработчику на этапе проектирования сразу понятно что будут проблемы по производительности.

**Comment by Muxa89** [comment]
То есть в целом назначение NumberCapacity я понял правильно. 
В таком случае я бы предложил более явно выделить слой персистентности. Пока не прикрутишь настоящую БД все будет одной большой заглушкой. А внутри этой заглушки будет этот класс.

**Comment by Alexander512023** [comment]
> А, то есть кэш это не имитация персистентности?
> А зачем он тогда нужен? Кэш обычно добавляется сверху существующего приложения, если есть проблемы по производительности. Ну или если разработчику на этапе проектирования сразу понятно что будут проблемы по производительности.

Да, кэш между репозиторием и dao у меня поместился. То есть репозиторий обращается в кэш за данными - кэш если есть отдает, если нет - лезет в DAO. Ну и очищаем мы его при внесении изменений, чтобы не отдать не персистентные значения.
Одна из основных целей проекта - потренировать многопоточность. Кэш самая интересная с этой точки зрения штука на мой взгляд.

**Comment by Alexander512023** [comment]
> То есть в целом назначение NumberCapacity я понял правильно.
> В таком случае я бы предложил более явно выделить слой персистентности. Пока не прикрутишь настоящую БД все будет одной большой заглушкой. А внутри этой заглушки будет этот класс.

У меня как бы есть моя база и есть стороннее приложение NumberCapacity - я специально хотел тут все это разделить, типа чтобы разные сценарии сэмулировать.

**Comment by Muxa89** [comment]
> > То есть в целом назначение NumberCapacity я понял правильно.
> > В таком случае я бы предложил более явно выделить слой персистентности. Пока не прикрутишь настоящую БД все будет одной большой заглушкой. А внутри этой заглушки будет этот класс.
> 
> У меня как бы есть моя база и есть стороннее приложение NumberCapacity - я специально хотел тут все это разделить, типа чтобы разные сценарии сэмулировать.

Ничего не понял)) Будем обсуждать очно)

**Comment by Muxa89** [comment]
> > А, то есть кэш это не имитация персистентности?
> > А зачем он тогда нужен? Кэш обычно добавляется сверху существующего приложения, если есть проблемы по производительности. Ну или если разработчику на этапе проектирования сразу понятно что будут проблемы по производительности.
> 
> Да, кэш между репозиторием и dao у меня поместился. То есть репозиторий обращается в кэш за данными - кэш если есть отдает, если нет - лезет в DAO. Ну и очищаем мы его при внесении изменений, чтобы не отдать не персистентные значения. Одна из основных целей проекта - потренировать многопоточность. Кэш самая интересная с этой точки зрения штука на мой взгляд.

Дело, конечно, твое, но чем больше элементов в системе - тем скорее они запутаются между собой. Поэтому я бы для начала реализовал базовый цикл работы с данными: запрос - контроллер - бизнес-логика - дао - бд, а потом уже накручивал кэш.

**Comment by Alexander512023** [comment]
Если речь о сложносочиненном номере счета - тогда я вообще бы вынес это все в отдельную сущность.
Получается что будет или есть какой-то выделенный генератор этих счетов. Генератор будет работать по своим правилам, которые прямого отношения к счету не имеют.
И эти правила имеет смысл вынести в отдельный пласт логики приложения.

**Comment by Alexander512023** [comment]
1. Создать отдельный интерфейс для репозитория номерной емкости.
2. Реализовать интерфейс через заглушку, которая собирает номер счета, в т.ч. числовую часть берет через обращение в номерную емкость через очереди, по принципу producer-consumer.
3. Реализовать класс номерной емкости, который обрабатывает задачи по принципу producer-consumer.

**Comment by Alexander512023** [comment]
> * Создать отдельный интерфейс для репозитория номерной емкости.
> * Реализовать интерфейс через заглушку, которая собирает номер счета, в т.ч. числовую часть берет через обращение в номерную емкость через очереди, по принципу producer-consumer.
> * Реализовать класс номерной емкости, который обрабатывает задачи по принципу producer-consumer.

b6efec9
