### ISSUE TITLE
Исчезли зависимости Cache

### ISSUE THREAD

**Issue by Muxa89** [Alexander512023/bank#8]
С комитом "Fixed enrich/complete methods in AccountService" поудалялись зависимости связанные с кэшем.

<img width="442" alt="Снимок экрана 2023-01-13 в 09 34 28" src="https://user-images.githubusercontent.com/1621669/212244984-61b8e10d-4ba8-4014-80b7-cc30460607e7.png">
<img width="1050" alt="Снимок экрана 2023-01-13 в 09 35 54" src="https://user-images.githubusercontent.com/1621669/212245085-e4febc73-3675-4d0f-a62b-957ac6123c98.png">

**Comment by Alexander512023** [comment]
Они скорее появились - я общую часть, спецификацию самого кэша вынес в отдельный проект. Его тут же выложил https://github.com/Alexander512023/cache

**Comment by Muxa89** [comment]
> Они скорее появились - я общую часть, спецификацию самого кэша вынес в отдельный проект. Его тут же выложил https://github.com/Alexander512023/cache

404 по ссылке. Может он у тебя private?

**Comment by Alexander512023** [comment]
> > Они скорее появились - я общую часть, спецификацию самого кэша вынес в отдельный проект. Его тут же выложил https://github.com/Alexander512023/cache
> 
> 404 по ссылке. Может он у тебя private?

Это он у меня за ночь мысленно на гите появился) добавил
