### ISSUE TITLE
Работа с ветками

### ISSUE THREAD

**Issue by Muxa89** [Alexander512023/bank#9]
Как у тебя такая структура веток получилась? Это было целенаправленно или с гитом не разобрался?

<img width="753" alt="Снимок экрана 2023-01-13 в 09 37 41" src="https://user-images.githubusercontent.com/1621669/212245293-75065549-38f8-4cd0-b99d-fa8086564cf7.png">

**Comment by Alexander512023** [comment]
Да, с гитом разбираюсь пока. Когда ридми добавлял - у меня пушиться перестал проект. Поэтому там пришлось фетч и мердж делать, результаты чего выглядят таким образом)
